version: "3.8"

services:
  cnab-webserver:
    build: .docker/bin/webserver
    container_name: 'cnab-webserver'
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_BIND-127.0.0.1}:${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_BIND-127.0.0.1}:${HOST_MACHINE_SECURE_HOST_PORT}:443"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-.docker/logs/apache2}:/var/log/apache2
  cnab-mysql:
    build: .docker/bin/mysql
    container_name: 'cnab-mysql'
    restart: 'always'
    command: --sql_mode="" --optimizer_switch="index_merge_intersection=off"
    ports:
      - "${HOST_MACHINE_MYSQL_BIND-127.0.0.1}:${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-.docker/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-.docker/logs/mysql}:/var/log/mysql
      - ${MYSQL_INIT_DIR-.docker/config/mysql/initdb.sql}:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  payment-processor:
    build: payment-processor
    container_name: 'payment-processor'
    restart: 'always'
    ports:
      - "5048:80"
    volumes:
      - ./cnab_files_transfer:/payment-processor/cnab_files_transfer
